-- garment.archived (boolean) becomes garment.status: wishlist, closet or
-- archived (#18; the state machine is src/wardrobe/status.ts). Generated by
-- drizzle-kit in two steps (the new columns, then the old one's drop, so it
-- never asked whether status was archived renamed); the data step is
-- hand-written.
--
-- Every existing garment is owned: archived true becomes 'archived', false
-- 'closet' (the column default); nothing becomes a wishlist item. archived
-- has been NOT NULL since the baseline, so the mapping is total and needs no
-- guard. One transaction with the rest of the batch: a failure leaves the
-- column as it was (test/integration/garment-status-migration.spec.ts).
ALTER TABLE "garment" ADD COLUMN "status" text DEFAULT 'closet' NOT NULL;--> statement-breakpoint
UPDATE "garment" SET "status" = 'archived' WHERE "archived";--> statement-breakpoint
ALTER TABLE "garment" ADD CONSTRAINT "garment_status_check" CHECK ("garment"."status" in ('wishlist', 'closet', 'archived'));--> statement-breakpoint
-- The grid's keyset index, rebuilt on the status.
DROP INDEX "garment_owner_id_archived_id_index";--> statement-breakpoint
CREATE INDEX "garment_owner_id_status_id_index" ON "garment" USING btree ("owner_id","status","id" DESC NULLS LAST);--> statement-breakpoint
ALTER TABLE "garment" DROP COLUMN "archived";--> statement-breakpoint
-- What a wishlist item replaces (a garment of the same owner; the writers'
-- rule). No row has one yet.
ALTER TABLE "garment" ADD COLUMN "replaces_garment_id" integer;--> statement-breakpoint
ALTER TABLE "garment" ADD CONSTRAINT "garment_replaces_garment_id_foreign" FOREIGN KEY ("replaces_garment_id") REFERENCES "public"."garment"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "garment_replaces_garment_id_index" ON "garment" USING btree ("replaces_garment_id");--> statement-breakpoint
ALTER TABLE "garment" ADD CONSTRAINT "garment_replaces_garment_id_check" CHECK ("garment"."replaces_garment_id" <> "garment"."id");
