-- Garment colours become a set, text[], like materials and plan_item.colors
-- (#28): the grid filters with @> as it does materials, the check below
-- keeps the colour set in the database, and nothing splits a string.
-- Generated by drizzle-kit (the add and the check, then the drop in a second
-- run, merged: an add and a drop in one table make it prompt for a rename),
-- then edited: the guard and the conversion are hand-written. The snapshot
-- is drizzle-kit's own, and a further `drizzle-kit generate` finds nothing
-- to do.
ALTER TABLE "garment" ADD COLUMN "colors" text[];--> statement-breakpoint
-- Guard: abort (the batch rolls back, the boot fails) rather than drop a
-- colour someone chose. The garment form has stored only built-in names
-- since drizzle/0004_garment_web.sql, which checked the same list; each item
-- is compared trimmed and lower case, and a blank item (a trailing comma,
-- an empty string) is nothing. The list is GARMENT_COLORS
-- (src/wardrobe/properties.ts) as of this migration, frozen here like every
-- migration's SQL.
DO $$
DECLARE
  offending text;
BEGIN
  SELECT string_agg(format('%s (%L)', "g"."id", "g"."color"), ', ' ORDER BY "g"."id")
    INTO offending
    FROM "garment" AS "g"
    WHERE EXISTS (
      SELECT 1
        FROM unnest(string_to_array("g"."color", ',')) AS "t"("token")
       WHERE lower(btrim("t"."token", E' \t\r\n')) <> ''
         AND lower(btrim("t"."token", E' \t\r\n')) NOT IN ('red', 'pink',
           'orange', 'yellow', 'green', 'blue', 'purple', 'black', 'white',
           'grey', 'beige', 'brown', 'gold', 'silver', 'pattern', 'other')
    );
  IF offending IS NOT NULL THEN
    RAISE EXCEPTION 'garment: colours outside the built-in set in row(s) %. Replace them with built-in colours (other, say), then boot again.', offending;
  END IF;
END $$;--> statement-breakpoint
-- Each garment's colours as a set: in the list's order (the order the form's
-- checkboxes post), each once, and null for none (never an empty array).
UPDATE "garment" SET "colors" = NULLIF(ARRAY(
  SELECT "c"."name"
    FROM unnest(ARRAY['red', 'pink', 'orange', 'yellow', 'green', 'blue',
      'purple', 'black', 'white', 'grey', 'beige', 'brown', 'gold', 'silver',
      'pattern', 'other']) WITH ORDINALITY AS "c"("name", "n")
   WHERE "c"."name" IN (
     SELECT lower(btrim("t"."token", E' \t\r\n'))
       FROM unnest(string_to_array("garment"."color", ',')) AS "t"("token")
   )
   ORDER BY "c"."n"
), '{}')
WHERE "color" IS NOT NULL;--> statement-breakpoint
ALTER TABLE "garment" ADD CONSTRAINT "garment_colors_check" CHECK ("garment"."colors" <@ array['red', 'pink', 'orange', 'yellow', 'green', 'blue', 'purple', 'black', 'white', 'grey', 'beige', 'brown', 'gold', 'silver', 'pattern', 'other']::text[] and cardinality("garment"."colors") > 0);--> statement-breakpoint
ALTER TABLE "garment" DROP COLUMN "color";
