-- #175, the index audit. Generated by drizzle-kit; the comments are hand-written.
--
-- The garment keyset indexes become (…, id DESC), Postgres' own DESC order
-- (NULLS FIRST). They were id DESC NULLS LAST (Drizzle's index .desc()), an
-- order no query asks for: every orderBy(desc(garment.id)) is plain DESC, so
-- the planner could not read either index in order and scanned garment_pkey
-- backward, filtering out every other owner's garments.
-- wardrobe_share_grantor_id_index duplicated the leading column of
-- wardrobe_share_grantor_id_grantee_id_unique, which serves the grantor_id
-- foreign key and lookups alone.
--
-- Plain, not CONCURRENTLY: drizzle's migrator runs the pending files in one
-- transaction, where CONCURRENTLY cannot run. The locks last milliseconds:
-- production's garment table holds under 100 rows, wardrobe_share one.
--
-- Rollback (no down migrations): in a new migration, or by hand,
--   DROP INDEX garment_owner_id_status_id_index;
--   CREATE INDEX garment_owner_id_status_id_index ON garment (owner_id, status, id DESC NULLS LAST);
--   DROP INDEX garment_owner_id_category_id_index;
--   CREATE INDEX garment_owner_id_category_id_index ON garment (owner_id, category, id DESC NULLS LAST);
--   CREATE INDEX wardrobe_share_grantor_id_index ON wardrobe_share (grantor_id);
-- Both states return the same rows; only the plans differ.
DROP INDEX "wardrobe_share_grantor_id_index";--> statement-breakpoint
DROP INDEX "garment_owner_id_status_id_index";--> statement-breakpoint
DROP INDEX "garment_owner_id_category_id_index";--> statement-breakpoint
CREATE INDEX "garment_owner_id_status_id_index" ON "garment" USING btree ("owner_id","status","id" DESC NULLS FIRST);--> statement-breakpoint
CREATE INDEX "garment_owner_id_category_id_index" ON "garment" USING btree ("owner_id","category","id" DESC NULLS FIRST);